name: Secure Deploy Static App to EC2

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # STEP 1️⃣ - Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # STEP 2️⃣ - Secure Login + Build + Push
    - name: Login, Build and Push Docker Image
      run: |
        IMAGE_TAG=${{ github.sha }}
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" \
          --password-stdin

        docker build -t harisankarsundaram/my-html-app:$IMAGE_TAG .
        docker push harisankarsundaram/my-html-app:$IMAGE_TAG

        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # STEP 3️⃣ - Secure SSH Deploy
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker stop my-html-app || true
          docker rm my-html-app || true
          docker pull harisankarsundaram/my-html-app:${IMAGE_TAG}
          docker run -d \
            -p 80:80 \
            --restart unless-stopped \
            --name my-html-app \
            harisankarsundaram/my-html-app:${IMAGE_TAG}
